# Generated by Django 2.2 on 2019-11-03 18:12

from django.db import migrations


def create_profile(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


def drop_profile(apps, schema_editor):
    pass
    # Profile = apps.get_model('accounts', 'Profile')
    # Profile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profile, drop_profile)
    ]
